# Generated by Django 5.2 on 2025-05-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_consultamedica_alter_paciente_apellidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='activo',
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='examenes_pedidos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='indicaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='alergias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='medicamentos_habituales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='vacunas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_sangre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
